nelmio_api_doc:
    documentation:
        info:
            title: BilemoAPI
            description: API sécurisée permettant de consulter les produits de la marque Bilemo. La consultation nécessite d'être ajouté comme client par une personne habilitée.
            version: 1.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
